pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
              checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/nnnagamani/first-repo.git']])  
            }
        }
    }
}
